### ISSUE TITLE
konsole colors

### ISSUE THREAD

**Issue by mrturcot** [dpayne/cli-visualizer#189]
When I set `colors.override.terminal=false` & `colors.scheme=rainbow` in config, I have a dark red bar running through where light greenish color should be?

![vis](https://user-images.githubusercontent.com/3188835/129656174-c1f2c7a8-8b7a-40a9-be88-2190b79580a8.png)

I have not added `gradient=false` in any color scheme configs. I know its konsole acting up because with the same vis config the gradient is as expected in Yakuake.

![yak](https://user-images.githubusercontent.com/3188835/129656377-63b9546d-0056-49ea-88ab-c73351068cef.png)

Any help would be awesome, this is driving me nuts! In konsole I have TERM=rxvt-256color set, im using linux colors, and displaying 256 Colors looks fine otherwise.

**Comment by CocolinoFan** [comment]
So what happen with this? The issue is still there for sure. 
Changing colors.override.terminal=false and colors.scheme=rainbow gives weird and buggy colors,
The the bug in consistent.

My fix (is far from ideal):
-set "colors.override.terminal=false"
-comment out the "colors.scheme=rainbow"

It seams like the colors stay consistent with this config. The down side is, that at least on my terminal, the colors will be really really dark.

**Comment by Hex-4** [comment]
Yep, can confirm it's here too on Kubuntu 23.10.
