### ISSUE TITLE
feature request: UTF-8 chars and visualizer.*.character option

### ISSUE THREAD

**Issue by dasnoopy** [dpayne/cli-visualizer#30]
Hi... maybe a missed  something,  but it seems it isn't possible to use any UTF-8 char with  ` visualizer.[spectrum|ellipse|lorenz].character`  options

...should be nice have this.  :-)

thanks in advance 
Andrea

**Comment by dpayne** [comment]
This should work already. Please let me know if it doesn't.

**Comment by dasnoopy** [comment]
mhh.  Every utf-8 char I use

visualizer.spectrum.character=❚

**Comment by dpayne** [comment]
What happens if you just use the default, so remove any visualizer.*.character options? By default it should use the UTF-8 ❚ character.

**Comment by dasnoopy** [comment]
removing or commenting visualizer.*.character options,  everything works as expected using the default UTF-8 ❚ character...

![screenshot from 2016-11-09 07-00-05](https://cloud.githubusercontent.com/assets/296922/20128787/10fb14c4-a64b-11e6-9ee9-ab9964446533.png)

Andrea

**Comment by rhoeden** [comment]
I can reproduce this on my system as well (Arch Linux & cli-visualizer-git from aur). It seems to be connected with the terminal emulator because plain xterm (no .Xresources) works – without colors –  but termite or urxvt does not. The attached screenshot should display visualizer in the bundled Rainbow palette.

![2016-11-26-115007_484x316_scrot](https://cloud.githubusercontent.com/assets/10729640/20639519/b163f01c-b3ce-11e6-8b6b-f02910534b11.png)

**Comment by dpayne** [comment]
Currently it doesn't support utf-8 characters in the config. I'm looking at trying to fix it, haven't had time to look into a solution yet.

**Comment by dpayne** [comment]
This should work now, could you try the latest build?

**Comment by dasnoopy** [comment]
confirm that , after latest changes, UTF-8 char are supported with   `visualizer.[spectrum|ellipse|lorenz].character` config options... :)

Many thanks
Andrea
