### ISSUE TITLE
OSX audio output

### ISSUE THREAD

**Issue by gugica** [dpayne/cli-visualizer#35]
Hello. I got a bit confused at the setup section. I'm running MacOS and I don't know which audio output should I choose. 
Thanks for your answers.

**Comment by dpayne** [comment]
The visualizer on MacOS only works with mpd.  You can install it with homebrew, here is a good tutorial https://timothy.sh/article/install-mpd-ncmpcpp-on-osx-yosemite/.

Unfortunately due to MacOS's sound architecture there is no good way to hook into the sound system for the whole OS, so it's unlikely that the visualizer will ever support anything but mpd for MacOS.
