### ISSUE TITLE
Visualizer Lag/Delay

### ISSUE THREAD

**Issue by Se-Si** [dpayne/cli-visualizer#38]
Hi, thanks for the awesome visualizer. It's simple to use and one of the prettiest I've seen so far.

However, I couldn't help but notice an odd little delay between the notes actually playing in my ears and the movement/spikes of the visualizer (e.g. bass drum would come in for the first time but the visualizer would take a split second to actually react).

I'd really appreciate any thoughts on this! ^_^

**Comment by dpayne** [comment]
Are you using mpd or pulse?

**Comment by Se-Si** [comment]
pulse, sorry for the late response...

and thanks for the quick one =P

**Comment by dpayne** [comment]
I was hoping you were going to say mpd : ( Pulseaudio is a lot harder to tweak, I have very little control on the lag delay there. The one option that might help are cranking up the fps with `visualizer.fps=60`, the default is 20. The only other ways I know to tune the delay are to go into pulseaudio settings, which can get pretty complicated very quickly.

**Comment by Se-Si** [comment]
Oh I see... so if I may ask: does the visualizer get it's information pre-pulse delay or post-pulse delay? I suspect it'll be the second though I'm not too aware of how it works.

**Comment by dpayne** [comment]
So unfortunately it's actually dependent on a lot of different things ranging from your pulseaudio configs to your audio setup, which makes it pretty hard to debug. For example, if I bought a 1000ft audio cables for my speaks there would be a delay to the speakers but the visualizer wouldn't have the delay. This same issue happens with mpd, it's just easier to fix since mpd has a fairly simple config and so is easier to tweak.

I will say vis is _usually_ slower than pulse because of the buffer vis uses. Increasing the fps decreases the buffer size which usually makes the issue less noticeable. If you find vis being way ahead I could add a setting that will delay it by some configurable amount.

**Comment by Se-Si** [comment]
So for my problem it's the visualizer that's lagging so I'm sure the fps tweak should solve it. I'll try today and get back to you. If mpd is so much easier than pulse then I may consider just switching....

**Comment by dpayne** [comment]
@Se-Si did the fps change work?

**Comment by xxxserxxx** [comment]
I'd like to request the opposite.  Let me know if I should file a ticket for this.

I'd *like* a configurable lag.  In particular, I'm playing over a BT speaker in another room, and it has a full 2s lag between the mpd and when music comes out of the speaker.  I'd love to be able to tell **vis** to buffer the display by a configurable amount so that the display is sync'd with the audio.

I can probably figure out how to do this with pipes and a program in between, but having it as an option would be nice.
