### ISSUE TITLE
PKGBUILD for pacaur is broken

### ISSUE THREAD

**Issue by linuxundich** [dpayne/cli-visualizer#4]
Right now it's not possible to install cli-visualuzer from the AUR. Please take a look at the comments at https://aur.archlinux.org/packages/cli-visualizer

**Comment by dpayne** [comment]
can you try installing with yaourt?

**Comment by dpayne** [comment]
The build seems to be working for me, so I'm closing this for now. Please re-open if you still have issues.

**Comment by linuxundich** [comment]
Sorry, didn't much have time today. It looks like that yaourt works as AUR-Helper for cli-visualizer. When I use pacaur (like I usually do), it's says at the end that the packages has been installed, but the files are not there.

**Comment by StephenBrown2** [comment]
Which files? The package should install a binary in /usr/bin/vis, and supporting example files in /usr/share/doc/cli-visualizer

**Comment by linuxundich** [comment]
Pacaur fails installing...

```
$ pacaur -S cli-visualizer
[...]
  -> Generating .MTREE file...
  -> Compressing package...
==> Leaving fakeroot environment.
==> Finished making: cli-visualizer 1:321.bc0104e-1 (Di 2. Feb 15:17:23 CET 2016)
==> Cleaning up...
:: Installing cli-visualizer package(s)...
:: cli-visualizer package(s) failed to install. Check .SRCINFO for mismatching data with PKGBUILD.
$ pacman -Qi cli-visualizer
error: package 'cli-visualizer' was not found
```

I'm not sure, where I can find the mentioned  .SRCINFO

**Comment by StephenBrown2** [comment]
Here it is:
https://aur.archlinux.org/cgit/aur.git/tree/.SRCINFO?h=cli-visualizer

It's a hidden file (noted by the starting '.' in the filename), that is included in the package tarball itself, so wherever pacaur caches the packages it builds is where that will be.

Typically that is built from the PKGBUILD, however it's possible that the PKGBUILD was changed and the .SRCINFO wasn't updated.

I would read up on AUR packages to see where it might have failed, specifically this section of the wiki:
https://wiki.archlinux.org/index.php/Arch_User_Repository#AUR_metadata
which references mksrcinfo:
```The .SRCINFO can also be created from the PKGBUILD with mksrcinfo from pkgbuild-introspection.```

Once you locate pacaur's cache, or download the package source from the AUR, you can try making it yourself, generating a new .SRCINFO and comparing it with the one from the package.

**Comment by dpayne** [comment]
You are right that pacaur seems to fail because of the .SRCINFO. I had used mksrcinfo to generate the .SRCINFO so I had thought it should work, and it does seem to work with other AUR package managers.

The line pacaur fails on is

    [[ -z "${builtdepspkgs[@]}" && -z "${builtpkgs[@]}" ]] && Note "f" $"${colorW}${pkgsdeps[$i]}${reset} package(s) failed to install. Check .SRCINFO for mismatching data with PKGBUILD."

Which seems to have something to do with the dependencies in the `.SRCINFO`. I'm re-opening this for now until I can get it figured out. Let me know if you have any ideas.

**Comment by StephenBrown2** [comment]
It doesn't particularly help, but I used apacman to install it and it went fine. So maybe a bug in pacaur?

**Comment by dpayne** [comment]
Looks like it was mostly likely due to a pacaur bug. https://github.com/rmarquis/pacaur/issues/414 From the comments it looks like the fix will be out in the next stable release.

**Comment by rmarquis** [comment]
Nope, the mentioned fix doesn't concern your PKGBUILD; it's only fix installation of PKGBUILDs that redefine PKGEXT and override the makepkg config. Not sure if that would fix the issue, but your [pkgrel](https://wiki.archlinux.org/index.php/PKGBUILD#pkgrel) isn't standard.

**Comment by rmarquis** [comment]
The reason your package fails is because it is a `-git` package, although it does not have that extension. As a "stable" package, pacaur relies on the information provided by the RPC interface to retrieve the correct version.

I'd suggest you to rename your package to `cli-visualizer-git`, and keep `cli-visualizer` for the counterpart of the PKGBUILD. You should also use a standardized pkgrel, since `major.minor` seems however to be heavily discouraged, as per the comment in the wiki page history.

Note that yaourt and packer/apacman work here since they have fundamentally different way of working. Pacaur does not parse the PKGBUILDs at all to retrieve info, mostly for security purpose.

**Comment by dpayne** [comment]
Thanks so much for the comments here @rmarquis. I've created package `cli-visualizer-git` and as soon as I get a chance I'll change the PKGBUILD for `cli-visualizer` to use a stable package.
