### ISSUE TITLE
Unable to launch with terminator -e or --command

### ISSUE THREAD

**Issue by nanotron** [dpayne/cli-visualizer#45]
I have script which is intended to launch **vis** when I bring up my music player.  Unfortunately, the following commands result in an empty or blank Terminator screen. 

```
terminator -e vis
terminator --command vis
```

I've also tried this with i3-sensible-terminal.

Furthermore, I have tried launching **vis** via a specific Terminator profile but this produced the same result.  It's possible I'm missing something but any feedback would be greatly appreciated. Thank you.

Beyond this, I am able to launch **vis** just fine by itself.

**Comment by NeodarZ** [comment]
Hello,

I do that with a special layout for `vis` in terminator. Juste create new layout and tell him to execute a command instead of your shell. For me it's : `export TERM=xterm-256color; vis`

And when you want start this layout use this command : `terminator -l vis` (I name my layout `vis`)

If I use a special layout is because I change some design element like font size for `vis`.

But if I launch the same commands as you, it's work... Maybe your problem is like here : https://github.com/dpayne/cli-visualizer#vis-hangs-with-no-output
