### ISSUE TITLE
Add support for 24-bit True Color

### ISSUE THREAD

**Issue by hiteshpaul** [dpayne/cli-visualizer#58]
Now-a-days, majority of the terminal have support for true colors. To name few, below link will suffice:

https://gist.github.com/XVilka/8346728

It would be nice if we have true color support, as the color spectrum of the bars can be made to appear continous!

**Comment by dpayne** [comment]
This is a good idea, it shouldn't be too hard to implement. When I have a free weekend I'll look at implementing it.

**Comment by dpayne** [comment]
This turns out to be extremely difficult. Currently the visualizer users ncurses heavily and ncurses does not currently support 24bit color, and the maintainer has no plans to implement it anytime soon https://lists.gnu.org/archive/html/bug-ncurses/2013-10/msg00007.html. I'm looking at writing an ncurses extension to write 24 bit color but it has proven to be pretty problematic. Unless ncurses comes out with support for it I don't really see this happening any time soon.

I am planning on adding more color support so that it's easier to make gradients besides the default rainbow one. However this still won't be true 24 bit color.
