### ISSUE TITLE
vis breaks when pulseaudio server gets stopped

### ISSUE THREAD

**Issue by hahiserw** [dpayne/cli-visualizer#65]
It shouldn't really happen too often, but I think it should be handled.

Steps to reproduce:
1. Start pulseaudio server in one terminal
2. Start vis in another termianl
3. Stop pulseaudio server
4. Try to exit from vis by pressing Q or Ctrl+C to no avail

**Comment by dpayne** [comment]
Thanks for reporting this! I agree it is a legitimate issue, however I don't think the fix is worth handling this edge case. What's happening is that the visualizer is blocking waiting for input. The fix would be to do this in a separate thread and have the pulse audio reader do a non-blocking read from the pulse audio source. While this is possible, it doesn't seem worth the work. I'd happily merge a pull request if anyone wanted to code up the fix, but for now I am going to close this.

If you need to kill it, `kill -9 <pid>` will still work and not cause any issues.
