### ISSUE TITLE
Installing on macOS/make issues

### ISSUE THREAD

**Issue by sealevelcain** [dpayne/cli-visualizer#75]
I've installed all of the required dependencies via homebrew and downloaded the latest version of cli-vis from the releases page. Upon running install.sh I'm greeted with the following error:

```
make: *** No rule to make target `clean'.  Stop.
make: *** No targets specified and no makefile found.  Stop.
```
I am then prompted to enter my password. Upon doing so I receive: 
```
make: *** No rule to make target `install'.  Stop.
cp: examples/config: No such file or directory
cp: examples/rainbow: No such file or directory
cp: examples/basic_colors: No such file or directory
```

Am I missing something? I had a look round to find other issues with the installation process on mac but they didn't quite match. I installed Command Line Tools as suggested in some of the other issues but that didn't change anything.

**Comment by dpayne** [comment]
Do you mind posting the full build output and what mac os version you are running?

**Comment by sealevelcain** [comment]
Where do I found the build output? (new to this sorry). I'm running 10.12.6

**Comment by dpayne** [comment]
ah, I think I get what is going on. Instead of using release zip file or tar ball, could you directly use git instead? Github has some useful instructions for setting the repo up locally https://help.github.com/desktop/guides/contributing-to-projects/cloning-a-repository-from-github-to-github-desktop/. After you do that you can navigate to the directory and make should work.

**Comment by dpayne** [comment]
I'm closing this issue, let me know if the above solution didn't work for you.
