### ISSUE TITLE
Is there a way to use this in a tool-like fashion?

### ISSUE THREAD

**Issue by sorenbug** [dpayne/cli-visualizer#93]
It would be really cool if this program could just dump a static equalizer using `-w [columns] -h [rows]`. Most likely with no color-changing characters. Another option would be to when using small amounts for `-h` to use these unicode characters:

    U+2581 | ▁ | Lower one eighth block
    U+2582 | ▂ | Lower one quarter block
    U+2583 | ▃ | Lower three eighths block
    U+2584 | ▄ | Lower half block
    U+2585 | ▅ | Lower five eighths block
    U+2586 | ▆ | Lower three quarters block
    U+2587 | ▇ | Lower seven eighths block
    U+2588 | █ | Full block

An addition like this would allow me to put an equalizer in my i3bar, which currently looks like this:

![i3bar](https://i.gerdere.date/i/nplz.png)

`i3bar` only supports one line so the block characters would be perfect for that.

**Comment by dpayne** [comment]
Hi @sorenbug,

There is no way to use it as a tool right now. When writing it, I did try to keep in-mind doing something like this some day. If you are interested in coding it yourself, the starting point would be creating a new writer class and then integrating it into the main Visualizer class https://github.com/dpayne/cli-visualizer/tree/master/src/Writer.

As far as integrating it into i3bar. There's a chance this might work but there's a lot of hurdles to overcome. I think it would have to be a horizontal visualizer, meaning it goes from left to right instead of up and down. The visualizer uses ncurses and fonts to do the rendering so you really only have one character to work with per column, possible two or three if you can figure out how to shrink the font. The other challenge would be the frame rate. I don't know for sure, but I doubt many people render i3bar anywhere close to 20 frames per second. I don't want to discourage you too much, there _might_ be a way to get it to work, but it's going to take some work.

Another possibility would be to do something entirely different that achieves the same effect. The idea that immediately comes to mind is have create a very small terminal, set to borderless and transparent and with a very very small font. I think urxvt is capable of this. Then figure out a way to also keep it running at the bottom middle of the screen. I'm still not 100% sure this would work either since it has a lot of moving parts, but it might be more feasible than integrating directly with i3bar.

**Comment by sorenbug** [comment]
I would call the equalizer about 10 times per second using the same base as
sorenbug/spotifyi3 (which just calls spotify-cli). I'm not hoping for
anything that uses nurses, just the output at that time period of the
equalizer. (Which I could make a new writer for using the block characters)
